name: Build and deploy to gh-pages
on:
   push:
     branches:
       - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v2.3.4

      - name: Install dependencies 🐄
        run: |
          sudo apt-get -y update
          sudo apt-get -y install python3-pip
          pip install mkdocs-material==7.2.1 pygments==2.9.0 mkdocs-redirects==1.0.3

      - name: Build site 🔧
        run: |
          mkdocs build --verbose --clean

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: site # The folder the action should deploy.
